### PR TITLE
Set up packaging with setup.cfg and introduce linters

### PR DESCRIPTION
**Pull request by eggplants**
I added and configured flake8 + black + isort + mypy to dev dependencies, pre-commit and CI.

---

And I moved package's metadata and configurations of linters from setup.py into setup.cfg.

### CODE REVIEW

**Comment by eggplants** [comment]
I'm ready for review!

**Comment by shadowmoose** [comment]
This is looking good. The lint test seems to be failing when I launch it. If you think this is only an issue within the PR context, I can merge and check then.

**Comment by eggplants** [comment]
Sorry, fixed.

**Comment by shadowmoose** [comment]
Looks like the linter is running now, but kicking up an error:
```
ERROR: /home/runner/work/pyderman/pyderman/pyderman/__init__.py Imports are incorrectly sorted and/or formatted.
--- /home/runner/work/pyderman/pyderman/pyderman/__init__.py:before	2022-04-24 08:55:06.155086
+++ /home/runner/work/pyderman/pyderman/pyderman/__init__.py:after	2022-04-24 08:55:20.126947
@@ -6,8 +6,8 @@
 import shutil
 import tarfile
 import zipfile
+from os.path import abspath, basename, dirname, isfile, join
 from types import ModuleType
-from os.path import abspath, basename, dirname, isfile, join
 
 from pyderman import drivers
 from pyderman.drivers import all_drivers, chrome, edge, firefox, opera, phantomjs
```

**Comment by shadowmoose** [comment]
Looks like that fixed everything. Thanks!

**Pull request merged**
